name: lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  shortenertest:
    runs-on: ubuntu-latest
    container: golang:1.22

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup linters
        run: |
          go install github.com/roblaszczak/go-cleanarch@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
      
      - name: Run linter
        run: |
          go run cmd/staticlint/*.go ./... 

          

      # - name: Setup go deps
      #   run: |
      #     go install golang.org/x/tools/cmd/goimports@latest

      # - name: Build server binary
      #   run: |
      #     cd cmd/shortener
      #     go build -buildvcs=false -o shortener

      # - name: "Code increment #1"
      #   run: |
      #     shortenertestbeta -test.v -test.run=^TestIteration1$ \
      #         -binary-path=cmd/shortener/shortener
